In [4]:
#imports
import torch
import numpy as np

In [6]:
#initializing a tensor from a python array
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
print(x_data)
#initializing a tensor from a numpy array
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
print(x_np)



tensor([[1, 2],
        [3, 4]])
tensor([[1, 2],
        [3, 4]])


In [15]:
#creating tensors by using other tensors as a base:
x_ones = torch.ones_like(x_data) # retains the properties of x_data
print(f"Ones Tensor: \n {x_ones}")
print(f"datatype: \n {x_ones.dtype}")
print(f"shape:\n{x_ones.shape}")
print(f"device:\n{x_ones.device}\n")
x_rand = torch.rand_like(x_data, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {x_rand} \n")

Ones Tensor: 
 tensor([[1, 1],
        [1, 1]])
datatype: 
 torch.int64
shape:
torch.Size([2, 2])
device:
cpu

Random Tensor: 
 tensor([[0.8831, 0.5770],
        [0.9379, 0.9917]]) 



In [ ]:
#moving tensors from cpu to gpu
print(f"before device (unaccelerated): {x_ones.device}")
print(f"accelerator: {torch.accelerator.current_accelerator()}")
x_ones = x_ones.to(torch.accelerator.current_accelerator())
print(f"after device (acclerated): {x_ones.device}")

before device (unaccelerated): cpu
accelerator: mps
after device (acclerated): mps:0
